name       : mesa-demos
version    : 8.4.0
release    : 75
source     :
    - https://mesa.freedesktop.org/archive/demos/mesa-demos-8.4.0.tar.bz2 : 01e99c94a0184e63e796728af89bfac559795fb2a0d6f506fa900455ca5fff7d
license    :
    - BSL-1.0
    - MIT
    - SGI-B-1.0
component  : xorg.display
summary    : Demonstrations of the Mesa3D Library
replaces   :
    - mesalib-demos
description: |
    Demonstrations of the Mesa3D Library
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(glu)
    - pkgconfig(libdrm)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xext)
setup      : |
    %configure
build      : |
    %make -C src/xdemos
install    : |
    install -D -d -m 00755 $installdir/usr/bin
    install -m 00755 src/xdemos/glx{gears,info} $installdir/usr/bin/.
