name       : mesa-demos
version    : 8.3.0
release    : 72
source     :
    - https://mesa.freedesktop.org/archive/demos/8.3.0/mesa-demos-8.3.0.tar.gz : 6127c5511e63447b28c2df735739de06c5d221f68e7671cc0ee446e605e92357
license    :
    - BSL-1.0
    - MIT
    - SGI-B-1.0
component  : xorg.display
summary    : Demonstrations of the Mesa3D Library
replaces   :
    - mesalib-demos
description: |
    Demonstrations of the Mesa3D Library
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(glu)
    - pkgconfig(libdrm)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xext)
setup      : |
    %configure
build      : |
    %make -C src/xdemos
install    : |
    install -D -d -m 00755 $installdir/usr/bin
    install -m 00755 src/xdemos/glx{gears,info} $installdir/usr/bin/.
